-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- -- DROP TABLE public.GradeSection CASCADE;
-- DROP TABLE public.users CASCADE;
-- DROP TABLE public.refresh_tokens CASCADE;
-- DROP TABLE public.directors CASCADE;
-- -- DROP TABLE public.SubjectResult CASCADE;
-- -- DROP TABLE public.StudentGrade CASCADE;
