-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE identity.roles
-- ADD CONSTRAINT school_role_name_unique UNIQUE (school_id, name);
