ALTER TABLE academic.teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE academic.classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE academic.sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE academic.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance.payments ENABLE ROW LEVEL SECURITY;
