-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TABLE student.Students (
--     id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     school_id UUID REFERENCES tenancy.schools(id),
--     admission_number TEXT,
--     first_name TEXT,
--     last_name TEXT,
--     gender TEXT,
--     date_of_birth DATE
-- );
