-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "academic"."academicyears" add column "status" text
--  null default 'active';
