-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TABLE identity.UserRoles (
--     id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     user_id UUID REFERENCES identity.users(id),
--     role_id UUID REFERENCES identity.roles(id)
-- );
