-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TABLE academic.Subjects (
--     id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     school_id UUID REFERENCES tenancy.schools(id),
--     name TEXT
-- );
